-- GENERADO por scripts/parse-agenda.mjs a partir de content/agenda.md. No editar a mano.
-- 6 bloques, 139 sesiones.
begin;

insert into public.blocks (id, title, goal, certification, certification_code, certification_day, total_days) values
  (1, 'IaC auditable', 'Otra persona despliega y destruye el repo con el README.', null, null, null, 30),
  (2, 'Arquitectura y SAP-C03', 'Diseño multi-account escrito y la certificación de architect.', 'AWS Solutions Architect Professional SAP-C03', 'SAP-C03', 29, 30),
  (3, 'Coste y primer servicio', 'Un informe de arquitectura y coste que se puede cobrar.', null, null, null, 20),
  (4, 'Seguridad de APIs', 'API multi-tenant explotada, corregida e informada.', null, null, null, 22),
  (5, 'Controles en el pull request', 'Un hallazgo alto no se fusiona.', null, null, null, 15),
  (6, 'Baseline AWS y Security Specialty', 'Un incidente de laboratorio corrido con runbook, y la certificación de seguridad.', 'AWS Certified Security Specialty SCS-C03', 'SCS-C03', 21, 22)
on conflict (id) do update set title = excluded.title, goal = excluded.goal, certification = excluded.certification,
  certification_code = excluded.certification_code, certification_day = excluded.certification_day, total_days = excluded.total_days;

insert into public.sessions (id, position, block_id, day, hours, title, description, links) values
  (1, 1, 1, 1, 2, 'Get Started de Terraform', 'Tutorial oficial hasta el primer apply en la cuenta de laboratorio.', '[{"url":"https://developer.hashicorp.com/terraform/tutorials/aws-get-started","label":"Get Started de Terraform"}]'::jsonb),
  (2, 2, 1, 2, 2, 'Variables y outputs', 'Saca los valores fijos a variables.tf y outputs.tf. Añade una validación.', '[]'::jsonb),
  (3, 3, 1, 3, 2, 'State local', 'terraform state list y show..gitignore de Terraform. El state no se sube.', '[]'::jsonb),
  (4, 4, 1, 4, 2, 'Módulos', 'Extrae un recurso a modules/ y llámalo desde la raíz.', '[{"url":"https://developer.hashicorp.com/terraform/tutorials/modules","label":"Módulos"}]'::jsonb),
  (5, 5, 1, 5, 3, 'Repo del proyecto', 'Crea secure-serverless: modules/, envs/lab, README con prerrequisitos, fmt y validate en verde.', '[]'::jsonb),
  (6, 6, 1, 6, 2, 'State remoto', 'Pasa el state a S3 con lock. Anota bucket y tabla. Tutorial Remote State de HashiCorp.', '[]'::jsonb),
  (7, 7, 1, 7, 2, 'IAM mínimo', 'Rol de Lambda con aws_iam_policy_document. Sin Action * ni Resource *.', '[]'::jsonb),
  (8, 8, 1, 8, 2, 'Lambda y API Gateway', 'Tutorial Deploy serverless with Lambda and API Gateway. Déjalo aplicado.', '[]'::jsonb),
  (9, 9, 1, 9, 2, 'DynamoDB y cola', 'Añade tabla y SQS. Diez líneas de flujo en el README.', '[]'::jsonb),
  (10, 10, 1, 10, 3, 'Healthcheck y budget', 'GET /health responde. Budget de 5 USD y alarma. Destroy si no lo usas entre sesiones.', '[]'::jsonb),
  (11, 11, 1, 11, 2, 'Plan en el pull request', 'GitHub Actions: fmt, validate y plan.', '[{"url":"https://docs.github.com/en/actions","label":"Plan en el pull request"}]'::jsonb),
  (12, 12, 1, 12, 2, 'OIDC', 'Rol de GitHub a AWS sin access keys.', '[{"url":"https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-aws","label":"OIDC"}]'::jsonb),
  (13, 13, 1, 13, 2, 'Checkov', 'Corrige un hallazgo.', '[{"url":"https://www.checkov.io/1.Welcome/Quick%20Start.html","label":"Checkov"}]'::jsonb),
  (14, 14, 1, 14, 2, 'Apply con aprobación', 'Apply solo en main, con environment protegido. Prueba un plan rechazado.', '[]'::jsonb),
  (15, 15, 1, 15, 3, 'Pipeline verde', 'PR de prueba con el plan pegado en el README.', '[]'::jsonb),
  (16, 16, 1, 16, 2, 'Evento entre funciones', 'Dos Lambdas unidas por SQS o EventBridge. La misma solicitud dos veces no duplica el efecto.', '[]'::jsonb),
  (17, 17, 1, 17, 2, 'Logs', 'Retención de 14 días. Un log JSON por request, sin datos de cliente.', '[]'::jsonb),
  (18, 18, 1, 18, 2, 'Drift', 'Cambia un tag en consola y recupéralo con plan y apply. Anota el comando.', '[]'::jsonb),
  (19, 19, 1, 19, 2, 'ADR de IaC', 'ADR-001: por qué Terraform en este repo. Media página.', '[]'::jsonb),
  (20, 20, 1, 20, 3, 'Diagrama y coste', 'Mermaid de API, Lambda, cola y tabla. Estimación de coste en el README.', '[]'::jsonb),
  (21, 21, 1, 21, 2, 'Recorte de IAM', 'Quita permisos que la función no usa. Plan limpio.', '[]'::jsonb),
  (22, 22, 1, 22, 2, 'Apply desde cero', 'Destroy y apply siguiendo solo el README. Anota cada paso que falló.', '[]'::jsonb),
  (23, 23, 1, 23, 2, 'README corregido', 'El apply desde cero no pide trucos.', '[]'::jsonb),
  (24, 24, 1, 24, 2, 'Lista de controles', 'Cifrado, acceso público bloqueado, logs, OIDC y Checkov, marcados en el README.', '[]'::jsonb),
  (25, 25, 1, 25, 3, 'Ensayo', 'Un pase completo en limpio. Tag v0.1. Destroy al acabar.', '[]'::jsonb),
  (26, 26, 1, 26, 2, 'Repaso del fallo', 'El punto que más costó, solo con la doc oficial.', '[]'::jsonb),
  (27, 27, 1, 27, 2, 'Import', 'Crea un recurso a mano e impórtalo.', '[]'::jsonb),
  (28, 28, 1, 28, 2, 'Prueba de plan', 'Un plan de ejemplo o un terraform test en verde. No reescribas lo que ya funciona.', '[]'::jsonb),
  (29, 29, 1, 29, 2, 'Oferta', 'Una página: entrega Terraform, alcance, exclusiones, rango de horas.', '[]'::jsonb),
  (30, 30, 1, 30, 3, 'Cierre', 'Si el README aún no basta para desplegar y destruir, se usa aquí. Si basta, no añadas alcance.', '[]'::jsonb),
  (31, 31, 2, 1, 2, 'Organizations', 'Lee la guía y dibuja management, security y workload. No despliegues Control Tower en una cuenta personal.', '[{"url":"https://docs.aws.amazon.com/organizations/latest/userguide/orgs_introduction.html","label":"Organizations"}]'::jsonb),
  (32, 32, 2, 2, 2, 'Diagrama de cuentas', 'Pasa el dibujo al README del proyecto 2.', '[]'::jsonb),
  (33, 33, 2, 3, 2, 'SCP', 'Dos políticas de ejemplo: denegar bucket público y denegar regiones fuera de una lista.', '[]'::jsonb),
  (34, 34, 2, 4, 2, 'Rol cross-account', 'Rol de solo lectura. Módulo y plan, aunque no tengas tres cuentas.', '[]'::jsonb),
  (35, 35, 2, 5, 2, 'ADR de cuentas', 'ADR-002: qué vive en cada cuenta. Media página.', '[]'::jsonb),
  (36, 36, 2, 6, 2, 'VPC', 'Subredes privadas y un endpoint de S3 o DynamoDB, sin NAT si no hace falta.', '[{"url":"https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html","label":"VPC"}]'::jsonb),
  (37, 37, 2, 7, 2, 'VPC en lab', 'Aplícala con budget. Destroy de lo que cobre en reposo.', '[]'::jsonb),
  (38, 38, 2, 8, 2, 'Security group', 'Solo el tráfico del API. Anótalo en el diagrama.', '[]'::jsonb),
  (39, 39, 2, 9, 2, 'CloudTrail', 'Trail hacia un bucket de logs, con política que impide borrar.', '[]'::jsonb),
  (40, 40, 2, 10, 2, 'Quién lee los logs', 'Diez líneas: qué rol puede leer el bucket y cuál no.', '[]'::jsonb),
  (41, 41, 2, 11, 2, 'RTO y RPO', 'Del API. Elige backup/restore o pilot light.', '[]'::jsonb),
  (42, 42, 2, 12, 2, 'ADR de resiliencia', 'Media página.', '[{"url":"https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/welcome.html","label":"ADR de resiliencia"}]'::jsonb),
  (43, 43, 2, 13, 2, 'Restore', 'Backup de la tabla y un restore en lab.', '[]'::jsonb),
  (44, 44, 2, 14, 2, 'Serverless Lens', 'Marca 10 preguntas contra tu stack.', '[{"url":"https://docs.aws.amazon.com/wellarchitected/latest/serverless-applications-lens/serverless-applications-lens.html","label":"Serverless Lens"}]'::jsonb),
  (45, 45, 2, 15, 2, 'Dos hallazgos', 'Corrige dos de la lens en Terraform.', '[]'::jsonb),
  (46, 46, 2, 16, 2, 'DLQ', 'En la cola, con alarma si tiene mensajes.', '[]'::jsonb),
  (47, 47, 2, 17, 2, 'Fallo forzado', 'Comprueba que el mensaje llega a la DLQ.', '[]'::jsonb),
  (48, 48, 2, 18, 2, 'Well-Architected escrito', 'Una página por pilar: seguridad, fiabilidad, coste.', '[]'::jsonb),
  (49, 49, 2, 19, 3, 'Diagrama vivo', 'Un solo diagrama de cuentas, actualizado. No crees otro.', '[]'::jsonb),
  (50, 50, 2, 20, 2, 'Guía SAP-C03', 'Lee los dominios.', '[{"url":"https://aws.amazon.com/certification/certified-solutions-architect-professional/","label":"Guía SAP-C03"}]'::jsonb),
  (51, 51, 2, 21, 2, 'Diez preguntas de diseño', 'Anota por qué falla la opción que elegiste.', '[]'::jsonb),
  (52, 52, 2, 22, 2, 'Diez de multi-account', 'Redes y cuentas. Misma regla.', '[]'::jsonb),
  (53, 53, 2, 23, 2, 'Diez de coste', 'Migración y coste. Misma regla.', '[]'::jsonb),
  (54, 54, 2, 24, 3, 'Simulacro 1', '20 preguntas cronometradas.', '[]'::jsonb),
  (55, 55, 2, 25, 2, 'Dominio flojo', 'Solo el que quedó por debajo del 70 %.', '[]'::jsonb),
  (56, 56, 2, 26, 3, 'Simulacro 2', 'Otras 20. Si sigue bajo 70 %, el día 27 es repaso y la cita se mueve.', '[]'::jsonb),
  (57, 57, 2, 27, 2, 'Huecos del diagrama', 'Lo que el simulacro dejó sin evidencia en el repo.', '[]'::jsonb),
  (58, 58, 2, 28, 2, 'Repaso de la guía', 'Guía oficial, no un banco nuevo.', '[]'::jsonb),
  (59, 59, 2, 29, 3, 'Examen SAP-C03', 'Día de la cita. Si el simulacro del día 26 quedó bajo 70 %, este día es repaso y la cita se mueve. No presentes SAP-C02.', '[]'::jsonb),
  (60, 60, 2, 30, 2, 'Después del examen', 'Anota lo que no supiste, sin violar el NDA. Tag del proyecto y oferta corta de review de arquitectura.', '[]'::jsonb),
  (61, 61, 3, 1, 2, 'Cost Explorer', 'Actívalo y crea un budget.', '[{"url":"https://docs.aws.amazon.com/cost-management/latest/userguide/ce-what-is.html","label":"Cost Explorer"}]'::jsonb),
  (62, 62, 3, 2, 2, 'Inventario', 'Coste por servicio de los últimos 30 días de la cuenta lab.', '[]'::jsonb),
  (63, 63, 3, 3, 2, 'Tags', 'owner, env y service en Terraform. Agrupa el coste por tag.', '[]'::jsonb),
  (64, 64, 3, 4, 2, 'Pilar de coste', 'Gasto ocioso y right-sizing.', '[{"url":"https://docs.aws.amazon.com/wellarchitected/latest/cost-optimization-pillar/welcome.html","label":"Pilar de coste"}]'::jsonb),
  (65, 65, 3, 5, 3, 'Plantilla', 'Alcance, exclusiones y tabla de servicios.', '[]'::jsonb),
  (66, 66, 3, 6, 2, 'Memoria de Lambda', 'Tabla de memoria frente a duración. No compres nada.', '[]'::jsonb),
  (67, 67, 3, 7, 2, 'Savings Plans', 'Punto de equilibrio de un compromiso de un año, con números de ejemplo.', '[]'::jsonb),
  (68, 68, 3, 8, 2, 'Hallazgos típicos', 'Transferencia de datos y logs sin retención, como recomendación.', '[]'::jsonb),
  (69, 69, 3, 9, 2, 'Anomalías', 'Una alerta de Cost Anomaly Detection.', '[]'::jsonb),
  (70, 70, 3, 10, 3, 'Tres recomendaciones', 'Cada una con ahorro, esfuerzo y riesgo.', '[]'::jsonb),
  (71, 71, 3, 11, 2, 'Resumen', 'Una página para alguien que no es ingeniero.', '[]'::jsonb),
  (72, 72, 3, 12, 2, 'Plan de 30 días', 'Qué se apaga, qué se mide y qué no se toca.', '[]'::jsonb),
  (73, 73, 3, 13, 2, 'Pricing Calculator', 'Una alternativa costeada.', '[{"url":"https://calculator.aws","label":"Pricing Calculator"}]'::jsonb),
  (74, 74, 3, 14, 2, 'Acceso del servicio', 'Qué rol read-only pides y qué no entra.', '[]'::jsonb),
  (75, 75, 3, 15, 3, 'Informe', 'Versión entregable. Oferta freelance actualizada.', '[]'::jsonb),
  (76, 76, 3, 16, 2, 'Ensayo', 'Reunión de resultados de 20 minutos, en voz alta.', '[]'::jsonb),
  (77, 77, 3, 17, 2, 'Corrección', 'Arregla lo que no pudiste explicar.', '[]'::jsonb),
  (78, 78, 3, 18, 2, 'Falso ocioso', 'Un recurso que parece apagable y no lo es.', '[]'::jsonb),
  (79, 79, 3, 19, 3, 'Cierre', 'Tag v0.1. Si ya se puede entregar, no añadas alcance.', '[]'::jsonb),
  (80, 80, 3, 20, 2, 'Hipótesis', 'El número que el informe afirma y no sostiene: añádelo o márcalo.', '[]'::jsonb),
  (81, 81, 4, 1, 2, 'Threat model', 'Cheat sheet de OWASP. Dibuja actor, dato y frontera de una API de adelantos.', '[{"url":"https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html","label":"Threat model"}]'::jsonb),
  (82, 82, 4, 2, 2, 'Amenazas', 'Cinco amenazas sobre ese dibujo, en tus palabras.', '[]'::jsonb),
  (83, 83, 4, 3, 2, 'Access control', 'PortSwigger, labs Apprentice.', '[{"url":"https://portswigger.net/web-security/access-control","label":"Access control"}]'::jsonb),
  (84, 84, 4, 4, 2, 'BOLA en notas', 'Ataque y corrección de un IDOR, escritos.', '[]'::jsonb),
  (85, 85, 4, 5, 2, 'JWT', 'PortSwigger JWT, Apprentice y un Practitioner.', '[{"url":"https://portswigger.net/web-security/jwt","label":"JWT"}]'::jsonb),
  (86, 86, 4, 6, 2, 'JWT en notas', 'Qué claim no se debe fiar y cómo se comprueba.', '[]'::jsonb),
  (87, 87, 4, 7, 2, 'Autenticación', 'PortSwigger authentication, labs Apprentice.', '[]'::jsonb),
  (88, 88, 4, 8, 2, 'Lógica de negocio', 'PortSwigger business logic, labs Apprentice. El fallo tiene que ser de dinero.', '[]'::jsonb),
  (89, 89, 4, 9, 2, 'Race conditions', 'PortSwigger race conditions.', '[{"url":"https://portswigger.net/web-security/race-conditions","label":"Race conditions"}]'::jsonb),
  (90, 90, 4, 10, 2, 'SSRF', 'PortSwigger SSRF, labs Apprentice.', '[]'::jsonb),
  (91, 91, 4, 11, 2, 'API Top 10', 'Léela contra tu diseño.', '[{"url":"https://owasp.org/API-Security/","label":"API Top 10"}]'::jsonb),
  (92, 92, 4, 12, 2, 'ASVS', 'Capítulos de autenticación y acceso. Marca qué cumple y qué no.', '[]'::jsonb),
  (93, 93, 4, 13, 2, 'Repo vacío', 'API FastAPI, aviso de que será vulnerable a propósito. Datos falsos.', '[]'::jsonb),
  (94, 94, 4, 14, 3, 'BOLA implementado', 'Un comercio lee el recurso de otro.', '[]'::jsonb),
  (95, 95, 4, 15, 2, 'JWT débil', 'Algoritmo none o secreto en el repo, a propósito.', '[]'::jsonb),
  (96, 96, 4, 16, 2, 'Mass assignment', 'Un campo de rol o de tope que el cliente puede mandar.', '[]'::jsonb),
  (97, 97, 4, 17, 2, 'Sin rate limit', 'El endpoint de cotización no tiene tope.', '[]'::jsonb),
  (98, 98, 4, 18, 3, 'Evidencia', 'Request y response de cada hallazgo, en local. Nada contra un sistema ajeno.', '[]'::jsonb),
  (99, 99, 4, 19, 3, 'Corrección', 'Arregla los cuatro. Un test por hallazgo, que falle si vuelve.', '[]'::jsonb),
  (100, 100, 4, 20, 2, 'Retest', 'Los tests pasan y el exploit ya no funciona.', '[]'::jsonb),
  (101, 101, 4, 21, 3, 'Informe', 'Severidad, impacto, evidencia y remedio. Tag v0.1.', '[]'::jsonb),
  (102, 102, 4, 22, 2, 'Oferta de review', 'Una página: alcance, autorización escrita, qué no entra.', '[]'::jsonb),
  (103, 103, 5, 1, 2, 'Semgrep', 'Sobre la API corregida.', '[{"url":"https://semgrep.dev/docs/getting-started/","label":"Semgrep"}]'::jsonb),
  (104, 104, 5, 2, 2, 'Bandit', 'Compara un hallazgo con Semgrep.', '[]'::jsonb),
  (105, 105, 5, 3, 2, 'PR rojo', 'El workflow falla si hay un high confirmado.', '[]'::jsonb),
  (106, 106, 5, 4, 2, 'Excepción', 'Con fecha de vencimiento, escrita en el PR.', '[]'::jsonb),
  (107, 107, 5, 5, 3, 'Ejemplo', 'Un PR rojo y uno verde de muestra.', '[]'::jsonb),
  (108, 108, 5, 6, 2, 'Gitleaks', 'Pre-commit y CI. Un secreto de prueba no entra.', '[{"url":"https://github.com/gitleaks/gitleaks","label":"Gitleaks"}]'::jsonb),
  (109, 109, 5, 7, 2, 'Dependencias', 'pip-audit o Dependabot. Un aviso, aunque sea de prueba.', '[]'::jsonb),
  (110, 110, 5, 8, 2, 'Umbral', 'Qué se bloquea y qué solo se avisa.', '[]'::jsonb),
  (111, 111, 5, 9, 2, 'Rotación', 'El secreto de prueba se rota. No reescribas el historial.', '[]'::jsonb),
  (112, 112, 5, 10, 3, 'README', 'Los cuatro controles y el umbral.', '[]'::jsonb),
  (113, 113, 5, 11, 2, 'Checkov en el PR', 'Antes del plan, en el repo de Terraform.', '[]'::jsonb),
  (114, 114, 5, 12, 2, 'Hallazgo de IaC', 'Corrige uno o justifica la excepción.', '[]'::jsonb),
  (115, 115, 5, 13, 2, 'Plan bloqueado', 'No corre si Checkov falla en high.', '[]'::jsonb),
  (116, 116, 5, 14, 2, 'ADR', 'Por qué estos cuatro controles y no un scanner más.', '[]'::jsonb),
  (117, 117, 5, 15, 3, 'Tag', 'pipeline-v0.1. No añadas ZAP ni Cosign.', '[]'::jsonb),
  (118, 118, 6, 1, 2, 'CloudTrail', 'Trail en la cuenta lab, bucket sin borrado.', '[{"url":"https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-user-guide.html","label":"CloudTrail"}]'::jsonb),
  (119, 119, 6, 2, 2, 'Trail en Terraform', 'Que no viva solo en la consola.', '[]'::jsonb),
  (120, 120, 6, 3, 2, 'GuardDuty', 'Actívalo. Anota un finding de muestra.', '[]'::jsonb),
  (121, 121, 6, 4, 2, 'Security Hub', 'Qué finding te importa y cuál es ruido.', '[]'::jsonb),
  (122, 122, 6, 5, 2, 'KMS', 'Una clave para logs.', '[]'::jsonb),
  (123, 123, 6, 6, 2, 'Secrets Manager', 'El secreto sale del repo.', '[]'::jsonb),
  (124, 124, 6, 7, 2, 'Access Analyzer', 'Sobre el rol de Lambda. Cierra un finding o documéntalo.', '[]'::jsonb),
  (125, 125, 6, 8, 2, 'Config', 'Una regla: bucket público o security group abierto.', '[]'::jsonb),
  (126, 126, 6, 9, 2, 'Flow Logs', 'En la VPC de lab.', '[]'::jsonb),
  (127, 127, 6, 10, 2, 'WAF, solo criterio', 'Media página: cuándo va delante de API Gateway. No despliegues uno de pago si no lo vas a enseñar.', '[]'::jsonb),
  (128, 128, 6, 11, 2, 'Guion del incidente', 'Llave en un commit. Solo en lab.', '[]'::jsonb),
  (129, 129, 6, 12, 3, 'Correr el guion', 'Detección, contención, remediación. Anota la hora de cada paso.', '[]'::jsonb),
  (130, 130, 6, 13, 2, 'Runbook', 'El guion pasa a una página: quién hace qué.', '[]'::jsonb),
  (131, 131, 6, 14, 2, 'Segunda pasada', 'Corre el runbook otra vez y corrige lo que no se pudo seguir.', '[]'::jsonb),
  (132, 132, 6, 15, 2, 'Guía SCS-C03', 'Dominios de IAM y data protection.', '[{"url":"https://docs.aws.amazon.com/aws-certification/latest/security-specialty-03/security-specialty-03.html","label":"Guía SCS-C03"}]'::jsonb),
  (133, 133, 6, 16, 2, 'Quince preguntas', 'IAM y datos. Anota el fallo.', '[]'::jsonb),
  (134, 134, 6, 17, 2, 'Detection', 'Quince preguntas de detection e incident response. En inglés si el examen ya no está en español.', '[]'::jsonb),
  (135, 135, 6, 18, 3, 'Simulacro', '30 preguntas cronometradas.', '[]'::jsonb),
  (136, 136, 6, 19, 2, 'Dominio flojo', 'Solo el que quedó por debajo del 70 %.', '[]'::jsonb),
  (137, 137, 6, 20, 2, 'Repaso', 'Guía oficial, no un banco nuevo.', '[]'::jsonb),
  (138, 138, 6, 21, 3, 'Examen SCS-C03', 'Día de la cita. Solo si el baseline se probó y el simulacro del día 18 quedó por encima del 70 %. Si no, repaso y la cita se mueve. En inglés si es después del 31 de diciembre de 2026.', '[]'::jsonb),
  (139, 139, 6, 22, 2, 'Cierre', 'Anota huecos sin violar el NDA. Tag del baseline y oferta de assessment de una página.', '[]'::jsonb)
on conflict (id) do update set position = excluded.position, block_id = excluded.block_id, day = excluded.day, hours = excluded.hours,
  title = excluded.title, description = excluded.description, links = excluded.links;

commit;
